### ISSUE TITLE
Which course is this?

### ISSUE THREAD

**Issue by zuowanbushiwo** [Polochon-street/acoustics2017#1]
Hi
    Is this a speech signal processing class? Any details about it? I am very interested in it. Are there any other Lecture sources?

Thanks！

**Comment by Polochon-street** [comment]
Hi,

The exact name is "acoustic signal processing". It's a course I followed at Danmarks Tekniske Universitet, see the course page here: https://kurser.dtu.dk/course/2021-2022/22001?menulanguage=en.

I can't really give you more details, but perhaps you could contact the teacher, if you're interested in the course material :)

**Comment by zuowanbushiwo** [comment]
thanks!
